# Generated by Django 3.2.9 on 2021-11-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211107_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
